version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules
    stdin_open: true
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ["npm","run","test"]