language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ziham/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ziham/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  origin: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-894502452868"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
